"We’ve just finished school today.",
"I come from Merthyr, where the real Welsh people come from.",
"We can't have cakes, we're on the Herblife diet, where you just drink protein shakes.",
"Our family and friends and roots are here. We’re out in the sticks.",
"We feel like we’re country bumpkins.",
"We’ve been best friends since we were 11. And when we were about 17 I started dating her cousin, and I had my little girl. So now we’re family!",
"My daughter’s expecting twins. My grandson is interested in the castle.",
"I was born in Haverfordwest. When I was younger I didn’t appreciate it, all the history, the coast.",
"My roots are here and I don’t like it when people slag it off.",
"I only met some of these people today.",
"I’m feeling adventurous today!",
"I live nearby, about 10 miles away, we come for the shops, where we live it’s so rural … we come for the dentist.",
"How long have I lived here? The last ten years. Found it on the map, nothing dragged us. It’s somewhere so you’re not sat in the caravan all week.",
"We’ve been busy for 40 years, and the children have grown up now.",
"My mother lives here, we like shopping and the castle.",
"I’ve lived here a long time, since I was nine or ten years old.",
"I’m back from Birmingham now, though; I was homesick.",
"I’m from Portugal.",
"I knew some people.",
"I didn’t know people.",
"I’m what they call a Longneck; born in Haverfordwest and lived here all my life.",
"I’ve always thought it was the best town in Wales.",
"We live on the coast, it’s beautiful.",
"My friends are a funny group.",
"My father-in-law’s grandparents lived in Haverfordwest. His name was Owen.",
"We used to come years ago and it’s lovely to reminisce. My husband’s family are from here.",
"We’re from Treorchy.",
"I’ve lived this way since 1995. I’m from Cardiff originally; we’d always come to Pembrokeshire.",
"My Gran was friends with the milkman in Milford Haven and we’d stay in his house.",
"I'm from Milford.",
"I'm looking at the mortar rather than the bricks. It gives you a sense of belonging.",
"Nothing can substitute for being part of these ground roots.",
"I've been coming here for the last 20 years. We like to have a wander round, see what's changed.",
"I've come back to keep an eye on my mum and my best friend's had a daughter. She's got new finger paints!",
"He's a champion barman.",
"I'm from Hook originally, I know it here quite well.",
"I'm a village boy. This is a city as far as I'm concerned. I'm still a village boy. I've got work colleagues here.",
"My daughter's been here every year since she was born.",
"We met when I was on holiday in Hook.",
"I was born here. They usually call them Longnecks - something to do with the rivalry with Milford Haven, something to do with they like looking over garden walls; they're nosy, like.",
"I moved down from Newport, Gwent. My Dad works down here.",
"We moved about two years ago. At first I wanted to stay there. But I’ve made friends here now. The skate park’s helped.",
"I had an accident, broke my wrist, chipped my tooth. I was out of action for two weeks.",
"People are hypocrites.",
"She had her tail trodden on, things dropped on her head. She wasn’t bothered.",
"She just loves it, ‘cos she gets biscuits.",
"Friendly, even by mad Welsh standards.",
"It's a mix of boys and girls, different ages."
